const ErrorCodeEnum = {
    AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
    AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
    AUTH_NOT_FOUND: 'AUTH_NOT_FOUND',
    AUTH_TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
    AUTH_UNAUTHORIZED_ACCESS: 'AUTH_UNAUTHORIZED_ACCESS',
    AUTH_TOKEN_NOT_FOUND: 'AUTH_TOKEN_NOT_FOUND',

    //Rate limit errors
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

    // Upload/Image errors
    IMAGE_UPLOAD_FAILED: 'IMAGE_UPLOAD_FAILED',
    IMAGE_PROCESSING_FAILED: 'IMAGE_PROCESSING_FAILED',
    IMAGE_FORMAT_UNSUPPORTED: 'IMAGE_FORMAT_UNSUPPORTED',
    IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
    IMAGE_DIMENSION_INVALID: 'IMAGE_DIMENSION_INVALID',
    S3_UPLOAD_FAILED: 'S3_UPLOAD_FAILED',
    S3_DOWNLOAD_FAILED: 'S3_DOWNLOAD_FAILED',
    S3_DELETE_FAILED: 'S3_DELETE_FAILED',

    // Access Control Errors
    ACCESS_UNAUTHORIZED: 'ACCESS_UNAUTHORIZED',
    ACCESS_FORBIDDEN: 'ACCESS_FORBIDDEN',

    // Validation and Resource Errors
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

    // System Errors
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
}

module.exports = { ErrorCodeEnum }